### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by mrinalnilotpal** [Aniketkjnv/C_Programs#1]
try enriching your codes with proper documentation. It will provide other people get better intuition your code.

**Comment by mrinalnilotpal** [comment]
it will improve readability as well. right now it looks somewhat messy.

**Comment by crypticani** [comment]
Thanks for your piece of advice.
I am now writing codes with proper documentation wherever possible.
However, the older programs, like the programs in this repository is still without documentation.
I will try to add documentations to these programs too in my spare times.
